/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.spring;

import java.io.IOException;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import ru.otus.spring.service.QuestionService;

public class App {


    public static void main(String[] args) throws IOException {

    	ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("spring-context.xml");
    	QuestionService questionService = context.getBean(QuestionService.class);
    	questionService.printQuestions();
        context.close();    	
    }
}
